/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:47:15 GMT 2017
 */

package com.liferay.portal.kernel.annotation;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.annotation.Propagation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Propagation_ESTest extends Propagation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Propagation[] propagationArray0 = Propagation.values();
      assertNotNull(propagationArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Propagation propagation0 = Propagation.valueOf("REQUIRED");
      assertEquals(Propagation.REQUIRED, propagation0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Propagation propagation0 = Propagation.valueOf("NESTED");
      assertEquals(6, propagation0.value());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Propagation propagation0 = Propagation.REQUIRED;
      int int0 = propagation0.value();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Propagation propagation0 = Propagation.SUPPORTS;
      int int0 = propagation0.value();
      assertEquals(1, int0);
  }
}
