/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:50:10 GMT 2017
 */

package com.liferay.portal.kernel.googleapps.comparator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.googleapps.GUser;
import com.liferay.portal.kernel.googleapps.comparator.GUserLastNameComparator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GUserLastNameComparator_ESTest extends GUserLastNameComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GUserLastNameComparator gUserLastNameComparator0 = new GUserLastNameComparator();
      GUser gUser0 = new GUser();
      gUser0.setLastName("gbF?mDz8CtfFJh-L");
      GUser gUser1 = new GUser();
      gUser1.setLastName("Q=XAniOg :C|SKF");
      int int0 = gUserLastNameComparator0.compare(gUser0, gUser1);
      assertEquals(22, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GUserLastNameComparator gUserLastNameComparator0 = new GUserLastNameComparator();
      GUser gUser0 = new GUser();
      gUser0.setLastName("gbF?mDz8CtfFJh-L");
      GUser gUser1 = new GUser();
      gUser1.setLastName("Q=XAniOg :C|SKF");
      int int0 = gUserLastNameComparator0.compare(gUser1, gUser0);
      assertEquals((-22), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GUserLastNameComparator gUserLastNameComparator0 = new GUserLastNameComparator(false);
      GUser gUser0 = new GUser();
      // Undeclared exception!
      try { 
        gUserLastNameComparator0.compare(gUser0, gUser0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.comparator.GUserLastNameComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GUserLastNameComparator gUserLastNameComparator0 = new GUserLastNameComparator(false);
      GUser gUser0 = new GUser();
      gUser0.setLastName("");
      int int0 = gUserLastNameComparator0.compare(gUser0, gUser0);
      assertEquals(0, int0);
  }
}
