/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:49:48 GMT 2017
 */

package com.liferay.portal.kernel.googleapps.comparator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.googleapps.GUser;
import com.liferay.portal.kernel.googleapps.comparator.GUserFirstNameComparator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GUserFirstNameComparator_ESTest extends GUserFirstNameComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GUserFirstNameComparator gUserFirstNameComparator0 = new GUserFirstNameComparator();
      GUser gUser0 = new GUser();
      gUser0.setFirstName("M0[");
      GUser gUser1 = new GUser();
      gUser1.setFirstName("}s,NR=W ");
      int int0 = gUserFirstNameComparator0.compare(gUser1, gUser0);
      assertEquals(48, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GUserFirstNameComparator gUserFirstNameComparator0 = new GUserFirstNameComparator();
      GUser gUser0 = new GUser();
      gUser0.setFirstName("");
      GUser gUser1 = new GUser();
      gUser1.setFirstName("m0(j4}");
      int int0 = gUserFirstNameComparator0.compare(gUser0, gUser1);
      assertEquals((-6), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GUserFirstNameComparator gUserFirstNameComparator0 = new GUserFirstNameComparator();
      GUser gUser0 = new GUser();
      // Undeclared exception!
      try { 
        gUserFirstNameComparator0.compare(gUser0, gUser0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.comparator.GUserFirstNameComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GUserFirstNameComparator gUserFirstNameComparator0 = new GUserFirstNameComparator(false);
      GUser gUser0 = new GUser();
      gUser0.setFirstName("]'");
      int int0 = gUserFirstNameComparator0.compare(gUser0, gUser0);
      assertEquals(0, int0);
  }
}
