/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:50:00 GMT 2017
 */

package com.liferay.portal.kernel.googleapps.comparator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.googleapps.GUser;
import com.liferay.portal.kernel.googleapps.comparator.GUserFullNameComparator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GUserFullNameComparator_ESTest extends GUserFullNameComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GUserFullNameComparator gUserFullNameComparator0 = new GUserFullNameComparator();
      GUser gUser0 = new GUser();
      gUser0.setFirstName("$-QHlPjORO");
      gUser0.setLastName("$-QHlPjORO");
      GUser gUser1 = new GUser();
      gUser1.setFirstName("$-QHlPjORO");
      gUser1.setLastName("v #37}^Uy4puB;slr}U");
      int int0 = gUserFullNameComparator0.compare(gUser1, gUser0);
      assertEquals(82, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GUserFullNameComparator gUserFullNameComparator0 = new GUserFullNameComparator();
      GUser gUser0 = new GUser();
      gUser0.setFirstName("$-QHlPjORO");
      gUser0.setLastName("$-QHlPjORO");
      GUser gUser1 = new GUser();
      gUser1.setFirstName("$-QHlPjORO");
      gUser1.setLastName("v #37}^Uy4puB;slr}U");
      int int0 = gUserFullNameComparator0.compare(gUser0, gUser1);
      assertEquals((-82), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GUserFullNameComparator gUserFullNameComparator0 = new GUserFullNameComparator(false);
      GUser gUser0 = new GUser();
      // Undeclared exception!
      try { 
        gUserFullNameComparator0.compare(gUser0, gUser0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.GUser", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GUserFullNameComparator gUserFullNameComparator0 = new GUserFullNameComparator(false);
      GUser gUser0 = new GUser();
      gUser0.setLastName("");
      gUser0.setFirstName(" ");
      int int0 = gUserFullNameComparator0.compare(gUser0, gUser0);
      assertEquals(0, int0);
  }
}
