/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:51:19 GMT 2017
 */

package com.liferay.portal.kernel.googleapps.comparator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.googleapps.GUser;
import com.liferay.portal.kernel.googleapps.comparator.GUserUserIdComparator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GUserUserIdComparator_ESTest extends GUserUserIdComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GUserUserIdComparator gUserUserIdComparator0 = new GUserUserIdComparator();
      // Undeclared exception!
      try { 
        gUserUserIdComparator0.compare((GUser) null, (GUser) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.comparator.GUserUserIdComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GUserUserIdComparator gUserUserIdComparator0 = new GUserUserIdComparator(false);
      GUser gUser0 = new GUser();
      int int0 = gUserUserIdComparator0.compare(gUser0, gUser0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GUserUserIdComparator gUserUserIdComparator0 = new GUserUserIdComparator();
      GUser gUser0 = new GUser();
      gUser0.setUserId(1966L);
      GUser gUser1 = new GUser();
      int int0 = gUserUserIdComparator0.compare(gUser0, gUser1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GUserUserIdComparator gUserUserIdComparator0 = new GUserUserIdComparator();
      GUser gUser0 = new GUser();
      gUser0.setUserId(1966L);
      GUser gUser1 = new GUser();
      int int0 = gUserUserIdComparator0.compare(gUser1, gUser0);
      assertEquals((-1), int0);
  }
}
