/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:44:56 GMT 2017
 */

package com.liferay.portal.kernel.cluster;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import com.liferay.portal.kernel.cluster.ClusterEventListener;
import com.liferay.portal.kernel.cluster.ClusterExecutorUtil;
import com.liferay.portal.kernel.cluster.ClusterNode;
import com.liferay.portal.kernel.cluster.ClusterRequest;
import com.liferay.portal.kernel.cluster.FutureClusterResponses;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClusterExecutorUtil_ESTest extends ClusterExecutorUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = ClusterExecutorUtil.isClusterNodeAlive("K2($\"?#RH*I");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClusterExecutorUtil.initialize();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      List<ClusterNode> list0 = ClusterExecutorUtil.getClusterNodes();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FutureClusterResponses futureClusterResponses0 = ClusterExecutorUtil.execute((ClusterRequest) null);
      assertNull(futureClusterResponses0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ClusterExecutorUtil.destroy();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ClusterExecutorUtil.addClusterEventListener((ClusterEventListener) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ClusterEventListener clusterEventListener0 = mock(ClusterEventListener.class, new ViolatedAssumptionAnswer());
      ClusterExecutorUtil.removeClusterEventListener(clusterEventListener0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      boolean boolean0 = ClusterExecutorUtil.isEnabled();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ClusterNode clusterNode0 = ClusterExecutorUtil.getLocalClusterNode();
      assertNull(clusterNode0);
  }
}
