/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:43:36 GMT 2017
 */

package com.liferay.portal.kernel.cluster;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.cluster.ClusterException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClusterException_ESTest extends ClusterException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClusterException clusterException0 = new ClusterException();
      ClusterException clusterException1 = new ClusterException(clusterException0);
      assertFalse(clusterException1.equals((Object)clusterException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClusterException clusterException0 = new ClusterException(",9zsLN.u9Rvr,;");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClusterException clusterException0 = new ClusterException();
      ClusterException clusterException1 = new ClusterException(",9zsLN.u9Rvr,;", clusterException0);
      assertFalse(clusterException1.equals((Object)clusterException0));
  }
}
