/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:10:07 GMT 2017
 */

package com.liferay.portal.kernel.dao.db;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.dao.db.DBFactory;
import com.liferay.portal.kernel.dao.db.DBFactoryUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DBFactoryUtil_ESTest extends DBFactoryUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DBFactory dBFactory0 = DBFactoryUtil.getDBFactory();
      assertNull(dBFactory0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DBFactoryUtil dBFactoryUtil0 = new DBFactoryUtil();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        DBFactoryUtil.setDB("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.db.DBFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        DBFactoryUtil.getDB();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.db.DBFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DBFactoryUtil.setDBFactory((DBFactory) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        DBFactoryUtil.setDB((Object) "com.liferay.portal.kernel.dao.db.DBFactoryUtil");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.db.DBFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        DBFactoryUtil.getDB("com.liferay.portal.kernel.dao.db.DBFactoryUtil");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.db.DBFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        DBFactoryUtil.getDB(object0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.db.DBFactoryUtil", e);
      }
  }
}
