/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:27:42 GMT 2017
 */

package com.liferay.portal.kernel.cache.key;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.cache.key.CacheKeyGenerator;
import com.liferay.portal.kernel.cache.key.CacheKeyGeneratorUtil;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CacheKeyGeneratorUtil_ESTest extends CacheKeyGeneratorUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        CacheKeyGeneratorUtil.getCacheKeyGenerator("heg:$B-dQ?M/B");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.cache.key.CacheKeyGeneratorUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CacheKeyGeneratorUtil cacheKeyGeneratorUtil0 = new CacheKeyGeneratorUtil();
      HashMap<String, CacheKeyGenerator> hashMap0 = new HashMap<String, CacheKeyGenerator>();
      cacheKeyGeneratorUtil0.setCacheKeyGenerators(hashMap0);
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CacheKeyGeneratorUtil cacheKeyGeneratorUtil0 = new CacheKeyGeneratorUtil();
      cacheKeyGeneratorUtil0.setDefaultCacheKeyGenerator((CacheKeyGenerator) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        CacheKeyGeneratorUtil.getCacheKeyGenerator();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.cache.key.CacheKeyGeneratorUtil", e);
      }
  }
}
