/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:06:01 GMT 2017
 */

package com.liferay.portal.kernel.bi.reporting;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.bi.reporting.ReportExportException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReportExportException_ESTest extends ReportExportException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReportExportException reportExportException0 = new ReportExportException("PRi", (Throwable) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReportExportException reportExportException0 = new ReportExportException("PRi");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReportExportException reportExportException0 = new ReportExportException();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ReportExportException reportExportException0 = new ReportExportException((Throwable) null);
  }
}
