/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:08:28 GMT 2017
 */

package com.liferay.portal.kernel.bi.reporting;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.bi.reporting.ReportGenerationException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReportGenerationException_ESTest extends ReportGenerationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      ReportGenerationException reportGenerationException0 = new ReportGenerationException("F~", mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReportGenerationException reportGenerationException0 = new ReportGenerationException();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReportGenerationException reportGenerationException0 = new ReportGenerationException(" ");
      ReportGenerationException reportGenerationException1 = new ReportGenerationException(reportGenerationException0);
      assertFalse(reportGenerationException1.equals((Object)reportGenerationException0));
  }
}
