/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:21:55 GMT 2017
 */

package com.liferay.portal.kernel.dao.orm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.dao.orm.FinderCache;
import com.liferay.portal.kernel.dao.orm.FinderCacheUtil;
import com.liferay.portal.kernel.dao.orm.FinderPath;
import com.liferay.portal.kernel.dao.orm.SessionFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FinderCacheUtil_ESTest extends FinderCacheUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FinderCache finderCache0 = FinderCacheUtil.getFinderCache();
      assertNull(finderCache0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        FinderCacheUtil.removeCache(")j`M3uP~$^j");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.orm.FinderCacheUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        FinderCacheUtil.clearCache();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.orm.FinderCacheUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[21];
      Object object0 = FinderCacheUtil.getResult("7WGLL:|yFBc98Hsl", "", stringArray0, (Object[]) stringArray0, (SessionFactory) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        FinderCacheUtil.invalidate();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.orm.FinderCacheUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        FinderCacheUtil.clearLocalCache();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.orm.FinderCacheUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[5];
      FinderCacheUtil.putResult(true, "i'zrsxl~RB!d@1K.(L", "com.liferay.portal.kernel.dao.orm.FinderCacheUtil", stringArray0, (Object[]) stringArray0, (Object) "com.liferay.portal.kernel.dao.orm.FinderCacheUtil");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[2];
      FinderPath finderPath0 = new FinderPath(true, true, "B,Yy", "B,Yy", stringArray0);
      // Undeclared exception!
      try { 
        FinderCacheUtil.putResult(finderPath0, (Object[]) stringArray0, (Object) finderPath0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.orm.FinderCacheUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        FinderCacheUtil.clearCache("DR(G6+J,/");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.orm.FinderCacheUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Object[] objectArray0 = new Object[1];
      // Undeclared exception!
      try { 
        FinderCacheUtil.removeResult((FinderPath) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.orm.FinderCacheUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[9];
      FinderPath finderPath0 = new FinderPath(false, false, "Regenerate ", "Regenerate ", stringArray0);
      SessionFactory sessionFactory0 = mock(SessionFactory.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        FinderCacheUtil.getResult(finderPath0, (Object[]) stringArray0, sessionFactory0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.dao.orm.FinderCacheUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FinderCacheUtil finderCacheUtil0 = new FinderCacheUtil();
      finderCacheUtil0.setFinderCache((FinderCache) null);
  }
}
