/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:23:16 GMT 2017
 */

package com.liferay.portal.kernel.dao.orm;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.dao.orm.LockMode;
import com.liferay.portal.kernel.dao.orm.LockModeImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LockModeImpl_ESTest extends LockModeImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LockModeImpl lockModeImpl0 = new LockModeImpl("");
      String string0 = lockModeImpl0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LockModeImpl lockModeImpl0 = (LockModeImpl)LockMode.WRITE;
      String string0 = lockModeImpl0.getName();
      assertEquals("WRITE", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LockModeImpl lockModeImpl0 = new LockModeImpl((String) null);
      String string0 = lockModeImpl0.getName();
      assertNull(string0);
  }
}
