/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:23:24 GMT 2017
 */

package com.liferay.portal.kernel.dao.orm;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.dao.orm.ObjectNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ObjectNotFoundException_ESTest extends ObjectNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ObjectNotFoundException objectNotFoundException0 = new ObjectNotFoundException("gnon9@R+/;4Wjox");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ObjectNotFoundException objectNotFoundException0 = new ObjectNotFoundException();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ObjectNotFoundException objectNotFoundException0 = new ObjectNotFoundException((Throwable) null);
      ObjectNotFoundException objectNotFoundException1 = new ObjectNotFoundException("org.evosuite.runtime.mock.java.lang.MockThrowable: org.evosuite.runtime.mock.java.lang.MockThrowable", objectNotFoundException0);
      assertFalse(objectNotFoundException1.equals((Object)objectNotFoundException0));
  }
}
