/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:57:48 GMT 2017
 */

package com.liferay.portal.kernel.image;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.image.ImageBag;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ImageBag_ESTest extends ImageBag_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(3, 3, 3);
      ImageBag imageBag0 = new ImageBag(bufferedImage0, "mC!~4zGH");
      String string0 = imageBag0.getType();
      assertEquals("mC!~4zGH", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ImageBag imageBag0 = new ImageBag((RenderedImage) null, "");
      String string0 = imageBag0.getType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BufferedImage bufferedImage0 = new BufferedImage(3, 3, 3);
      ImageBag imageBag0 = new ImageBag(bufferedImage0, "mC!~4zGH");
      RenderedImage renderedImage0 = imageBag0.getRenderedImage();
      assertEquals(0, renderedImage0.getMinTileY());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ImageBag imageBag0 = new ImageBag((RenderedImage) null, (String) null);
      String string0 = imageBag0.getType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ImageBag imageBag0 = new ImageBag((RenderedImage) null, (String) null);
      RenderedImage renderedImage0 = imageBag0.getRenderedImage();
      assertNull(renderedImage0);
  }
}
