/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 01:00:13 GMT 2017
 */

package com.liferay.portal.kernel.image;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.image.SpriteProcessor;
import com.liferay.portal.kernel.image.SpriteProcessorUtil;
import java.io.File;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SpriteProcessorUtil_ESTest extends SpriteProcessorUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        SpriteProcessorUtil.generate((List<File>) null, "RJ-oYNL#K", "RJ-oYNL#K", "", 0, 0, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.image.SpriteProcessorUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<File> linkedList0 = new LinkedList<File>();
      // Undeclared exception!
      try { 
        SpriteProcessorUtil.generate(linkedList0, (String) null, "RL/g_R:h4}Q/nyOF!", (String) null, 2314, 2314, 2314);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.image.SpriteProcessorUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SpriteProcessor spriteProcessor0 = SpriteProcessorUtil.getSpriteProcessor();
      assertNull(spriteProcessor0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<File> linkedList0 = new LinkedList<File>();
      // Undeclared exception!
      try { 
        SpriteProcessorUtil.generate(linkedList0, "", "", "", 1861, 1, 1861);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.image.SpriteProcessorUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SpriteProcessorUtil spriteProcessorUtil0 = new SpriteProcessorUtil();
      spriteProcessorUtil0.setSpriteProcessor((SpriteProcessor) null);
  }
}
