/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:40:43 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.AddressZipException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AddressZipException_ESTest extends AddressZipException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddressZipException addressZipException0 = new AddressZipException();
      AddressZipException addressZipException1 = new AddressZipException("-Q^NI{L=mvQ.", addressZipException0);
      assertFalse(addressZipException1.equals((Object)addressZipException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AddressZipException addressZipException0 = new AddressZipException("org.evosuite.runtime.mock.java.lang.MockThrowable");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AddressZipException addressZipException0 = new AddressZipException();
      AddressZipException addressZipException1 = new AddressZipException(addressZipException0);
      assertFalse(addressZipException1.equals((Object)addressZipException0));
  }
}
