/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:41:06 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.CompanyVirtualHostException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompanyVirtualHostException_ESTest extends CompanyVirtualHostException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CompanyVirtualHostException companyVirtualHostException0 = new CompanyVirtualHostException("`yD9-'^<");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CompanyVirtualHostException companyVirtualHostException0 = new CompanyVirtualHostException();
      MockThrowable mockThrowable0 = new MockThrowable(companyVirtualHostException0);
      CompanyVirtualHostException companyVirtualHostException1 = new CompanyVirtualHostException(mockThrowable0);
      assertFalse(companyVirtualHostException1.equals((Object)companyVirtualHostException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CompanyVirtualHostException companyVirtualHostException0 = new CompanyVirtualHostException();
      CompanyVirtualHostException companyVirtualHostException1 = new CompanyVirtualHostException("|MS[~|\"wF<t", companyVirtualHostException0);
      assertFalse(companyVirtualHostException1.equals((Object)companyVirtualHostException0));
  }
}
