/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:40:59 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.CompanyMxException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompanyMxException_ESTest extends CompanyMxException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CompanyMxException companyMxException0 = new CompanyMxException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CompanyMxException companyMxException0 = new CompanyMxException("com.liferay.portal.CompanyMxException");
      CompanyMxException companyMxException1 = new CompanyMxException(companyMxException0);
      assertFalse(companyMxException1.equals((Object)companyMxException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CompanyMxException companyMxException0 = new CompanyMxException("com.liferay.portal.CompanyMxException");
      CompanyMxException companyMxException1 = new CompanyMxException("", companyMxException0);
      assertFalse(companyMxException1.equals((Object)companyMxException0));
  }
}
