/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:41:23 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.ContactBirthdayException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ContactBirthdayException_ESTest extends ContactBirthdayException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ContactBirthdayException contactBirthdayException0 = new ContactBirthdayException();
      ContactBirthdayException contactBirthdayException1 = new ContactBirthdayException("", contactBirthdayException0);
      assertFalse(contactBirthdayException1.equals((Object)contactBirthdayException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ContactBirthdayException contactBirthdayException0 = new ContactBirthdayException("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ContactBirthdayException contactBirthdayException0 = new ContactBirthdayException();
      ContactBirthdayException contactBirthdayException1 = new ContactBirthdayException(contactBirthdayException0);
      assertFalse(contactBirthdayException1.equals((Object)contactBirthdayException0));
  }
}
