/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:41:44 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.ContactFullNameException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ContactFullNameException_ESTest extends ContactFullNameException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ContactFullNameException contactFullNameException0 = new ContactFullNameException((String) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ContactFullNameException contactFullNameException0 = new ContactFullNameException();
      ContactFullNameException contactFullNameException1 = new ContactFullNameException("J\",6['`>]`L:", contactFullNameException0);
      assertFalse(contactFullNameException1.equals((Object)contactFullNameException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ContactFullNameException contactFullNameException0 = new ContactFullNameException();
      ContactFullNameException contactFullNameException1 = new ContactFullNameException(contactFullNameException0);
      assertFalse(contactFullNameException1.equals((Object)contactFullNameException0));
  }
}
