/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:42:42 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.CountryNumberException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CountryNumberException_ESTest extends CountryNumberException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CountryNumberException countryNumberException0 = new CountryNumberException((String) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CountryNumberException countryNumberException0 = new CountryNumberException();
      CountryNumberException countryNumberException1 = new CountryNumberException(countryNumberException0);
      assertFalse(countryNumberException1.equals((Object)countryNumberException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CountryNumberException countryNumberException0 = new CountryNumberException();
      CountryNumberException countryNumberException1 = new CountryNumberException("", countryNumberException0);
      assertFalse(countryNumberException1.equals((Object)countryNumberException0));
  }
}
