/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:42:17 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.CountryA3Exception;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CountryA3Exception_ESTest extends CountryA3Exception_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CountryA3Exception countryA3Exception0 = new CountryA3Exception("");
      CountryA3Exception countryA3Exception1 = new CountryA3Exception("", countryA3Exception0);
      assertFalse(countryA3Exception1.equals((Object)countryA3Exception0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CountryA3Exception countryA3Exception0 = new CountryA3Exception((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CountryA3Exception countryA3Exception0 = new CountryA3Exception();
  }
}
