/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:43:25 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.DuplicateRoleException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DuplicateRoleException_ESTest extends DuplicateRoleException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DuplicateRoleException duplicateRoleException0 = new DuplicateRoleException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DuplicateRoleException duplicateRoleException0 = new DuplicateRoleException((String) null);
      MockThrowable mockThrowable0 = new MockThrowable((String) null, duplicateRoleException0);
      DuplicateRoleException duplicateRoleException1 = new DuplicateRoleException(mockThrowable0);
      assertFalse(duplicateRoleException1.equals((Object)duplicateRoleException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DuplicateRoleException duplicateRoleException0 = new DuplicateRoleException((String) null);
      DuplicateRoleException duplicateRoleException1 = new DuplicateRoleException("", duplicateRoleException0);
      assertFalse(duplicateRoleException1.equals((Object)duplicateRoleException0));
  }
}
