/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:44:02 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.DuplicateUserIdException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DuplicateUserIdException_ESTest extends DuplicateUserIdException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DuplicateUserIdException duplicateUserIdException0 = new DuplicateUserIdException("x1j$@<@Wlyl;");
      DuplicateUserIdException duplicateUserIdException1 = new DuplicateUserIdException(duplicateUserIdException0);
      assertFalse(duplicateUserIdException1.equals((Object)duplicateUserIdException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DuplicateUserIdException duplicateUserIdException0 = new DuplicateUserIdException();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DuplicateUserIdException duplicateUserIdException0 = new DuplicateUserIdException("x1j$@<@Wlyl;");
      DuplicateUserIdException duplicateUserIdException1 = new DuplicateUserIdException("", duplicateUserIdException0);
      assertFalse(duplicateUserIdException1.equals((Object)duplicateUserIdException0));
  }
}
