/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:44:34 GMT 2017
 */

package com.liferay.portal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.GroupFriendlyURLException;
import com.liferay.portal.LayoutFriendlyURLException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GroupFriendlyURLException_ESTest extends GroupFriendlyURLException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GroupFriendlyURLException groupFriendlyURLException0 = new GroupFriendlyURLException((-2082));
      assertEquals(3, LayoutFriendlyURLException.TOO_SHORT);
  }
}
