/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:01:45 GMT 2017
 */

package com.liferay.portal.kernel.concurrent;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.concurrent.CompeteLatch;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompeteLatch_ESTest extends CompeteLatch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CompeteLatch competeLatch0 = new CompeteLatch();
      boolean boolean0 = competeLatch0.compete();
      boolean boolean1 = competeLatch0.compete();
      assertFalse(boolean1);
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CompeteLatch competeLatch0 = new CompeteLatch();
      boolean boolean0 = competeLatch0.compete();
      boolean boolean1 = competeLatch0.isLocked();
      assertTrue(boolean1);
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CompeteLatch competeLatch0 = new CompeteLatch();
      boolean boolean0 = competeLatch0.compete();
      boolean boolean1 = competeLatch0.done();
      assertTrue(boolean1 == boolean0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CompeteLatch competeLatch0 = new CompeteLatch();
      competeLatch0.await();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CompeteLatch competeLatch0 = new CompeteLatch();
      boolean boolean0 = competeLatch0.compete();
      TimeUnit timeUnit0 = TimeUnit.MICROSECONDS;
      boolean boolean1 = competeLatch0.await((-1791L), timeUnit0);
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CompeteLatch competeLatch0 = new CompeteLatch();
      boolean boolean0 = competeLatch0.isLocked();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CompeteLatch competeLatch0 = new CompeteLatch();
      boolean boolean0 = competeLatch0.done();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CompeteLatch competeLatch0 = new CompeteLatch();
      TimeUnit timeUnit0 = TimeUnit.MICROSECONDS;
      boolean boolean0 = competeLatch0.await((-1791L), timeUnit0);
      assertTrue(boolean0);
  }
}
