/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:22:38 GMT 2017
 */

package com.liferay.portal.kernel.cache.cluster;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.cache.cluster.PortalCacheClusterException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PortalCacheClusterException_ESTest extends PortalCacheClusterException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PortalCacheClusterException portalCacheClusterException0 = new PortalCacheClusterException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      PortalCacheClusterException portalCacheClusterException0 = new PortalCacheClusterException(mockThrowable0);
      PortalCacheClusterException portalCacheClusterException1 = new PortalCacheClusterException("S.'-wa!`KR-", portalCacheClusterException0);
      assertFalse(portalCacheClusterException1.equals((Object)portalCacheClusterException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PortalCacheClusterException portalCacheClusterException0 = new PortalCacheClusterException("U;;G~zwD]ES0");
  }
}
