/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:22:25 GMT 2017
 */

package com.liferay.portal.kernel.cache.cluster;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.cache.cluster.PortalCacheClusterEvent;
import com.liferay.portal.kernel.cache.cluster.PortalCacheClusterEventCoalesceComparator;
import com.liferay.portal.kernel.cache.cluster.PortalCacheClusterEventType;
import java.io.Serializable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PortalCacheClusterEventCoalesceComparator_ESTest extends PortalCacheClusterEventCoalesceComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PortalCacheClusterEventCoalesceComparator portalCacheClusterEventCoalesceComparator0 = new PortalCacheClusterEventCoalesceComparator();
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.UPDATE;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent((String) null, (Serializable) null, portalCacheClusterEventType0);
      // Undeclared exception!
      try { 
        portalCacheClusterEventCoalesceComparator0.compare(portalCacheClusterEvent0, portalCacheClusterEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.REMOVE;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("rkZo0t~N,", portalCacheClusterEventType0, portalCacheClusterEventType0);
      PortalCacheClusterEvent portalCacheClusterEvent1 = new PortalCacheClusterEvent("rkZo0t~N,", portalCacheClusterEvent0, portalCacheClusterEventType0);
      PortalCacheClusterEventCoalesceComparator portalCacheClusterEventCoalesceComparator0 = new PortalCacheClusterEventCoalesceComparator();
      int int0 = portalCacheClusterEventCoalesceComparator0.compare(portalCacheClusterEvent0, portalCacheClusterEvent1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PortalCacheClusterEventCoalesceComparator portalCacheClusterEventCoalesceComparator0 = new PortalCacheClusterEventCoalesceComparator();
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.EVICTED;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("P", "P", portalCacheClusterEventType0);
      PortalCacheClusterEvent portalCacheClusterEvent1 = new PortalCacheClusterEvent("O", portalCacheClusterEventType0, portalCacheClusterEventType0);
      int int0 = portalCacheClusterEventCoalesceComparator0.compare(portalCacheClusterEvent1, portalCacheClusterEvent0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PortalCacheClusterEventCoalesceComparator portalCacheClusterEventCoalesceComparator0 = new PortalCacheClusterEventCoalesceComparator();
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.UPDATE;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("<Mg3zcqc E* gE", portalCacheClusterEventType0, portalCacheClusterEventType0);
      int int0 = portalCacheClusterEventCoalesceComparator0.compare(portalCacheClusterEvent0, (PortalCacheClusterEvent) null);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PortalCacheClusterEventCoalesceComparator portalCacheClusterEventCoalesceComparator0 = new PortalCacheClusterEventCoalesceComparator();
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.EVICTED;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("P", "P", portalCacheClusterEventType0);
      int int0 = portalCacheClusterEventCoalesceComparator0.compare(portalCacheClusterEvent0, portalCacheClusterEvent0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PortalCacheClusterEventCoalesceComparator portalCacheClusterEventCoalesceComparator0 = new PortalCacheClusterEventCoalesceComparator();
      int int0 = portalCacheClusterEventCoalesceComparator0.compare((PortalCacheClusterEvent) null, (PortalCacheClusterEvent) null);
      assertEquals(1, int0);
  }
}
