/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:21:15 GMT 2017
 */

package com.liferay.portal.kernel.cache.cluster;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.cache.cluster.PortalCacheClusterEvent;
import com.liferay.portal.kernel.cache.cluster.PortalCacheClusterEventType;
import java.io.Serializable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PortalCacheClusterEvent_ESTest extends PortalCacheClusterEvent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent(":java.lang.String@0000000004:PUT", ":java.lang.String@0000000004:PUT", (PortalCacheClusterEventType) null);
      portalCacheClusterEvent0.getEventType();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.REMOVE;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent((String) null, (Serializable) null, portalCacheClusterEventType0);
      Serializable serializable0 = portalCacheClusterEvent0.getElementKey();
      assertNull(serializable0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.REMOVEALL;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent((String) null, portalCacheClusterEventType0, portalCacheClusterEventType0);
      String string0 = portalCacheClusterEvent0.getCacheName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.REMOVE;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("6l$et3Td4LD^PdD^2", "6l$et3Td4LD^PdD^2", portalCacheClusterEventType0);
      String string0 = portalCacheClusterEvent0.getCacheName();
      assertEquals("6l$et3Td4LD^PdD^2", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.REMOVEALL;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent((String) null, (Serializable) null, portalCacheClusterEventType0);
      // Undeclared exception!
      try { 
        portalCacheClusterEvent0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.UPDATE;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent((String) null, (Serializable) null, portalCacheClusterEventType0);
      // Undeclared exception!
      try { 
        portalCacheClusterEvent0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.EVICTED;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      PortalCacheClusterEventType portalCacheClusterEventType1 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent1 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType1);
      boolean boolean0 = portalCacheClusterEvent0.equals(portalCacheClusterEvent1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      PortalCacheClusterEvent portalCacheClusterEvent1 = new PortalCacheClusterEvent("", portalCacheClusterEventType0, portalCacheClusterEventType0);
      boolean boolean0 = portalCacheClusterEvent0.equals(portalCacheClusterEvent1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      PortalCacheClusterEvent portalCacheClusterEvent1 = new PortalCacheClusterEvent(":java.lang.String@0000000004:PUT", ":java.lang.String@0000000004:PUT", (PortalCacheClusterEventType) null);
      boolean boolean0 = portalCacheClusterEvent0.equals(portalCacheClusterEvent1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      Object object0 = new Object();
      boolean boolean0 = portalCacheClusterEvent0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.UPDATE;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent((String) null, (Serializable) null, portalCacheClusterEventType0);
      boolean boolean0 = portalCacheClusterEvent0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      boolean boolean0 = portalCacheClusterEvent0.equals(portalCacheClusterEvent0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.EXPIRED;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      portalCacheClusterEvent0.hashCode();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      String string0 = portalCacheClusterEvent0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      PortalCacheClusterEventType portalCacheClusterEventType1 = portalCacheClusterEvent0.getEventType();
      assertEquals(PortalCacheClusterEventType.PUT, portalCacheClusterEventType1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      Serializable serializable0 = portalCacheClusterEvent0.getElementKey();
      assertEquals("", serializable0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PortalCacheClusterEventType portalCacheClusterEventType0 = PortalCacheClusterEventType.PUT;
      PortalCacheClusterEvent portalCacheClusterEvent0 = new PortalCacheClusterEvent("", "", portalCacheClusterEventType0);
      String string0 = portalCacheClusterEvent0.getCacheName();
      assertEquals("", string0);
  }
}
