/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:43:36 GMT 2017
 */

package com.liferay.portal.kernel.deploy.sandbox;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.deploy.sandbox.SandboxDeployException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SandboxDeployException_ESTest extends SandboxDeployException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SandboxDeployException sandboxDeployException0 = new SandboxDeployException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SandboxDeployException sandboxDeployException0 = new SandboxDeployException("");
      SandboxDeployException sandboxDeployException1 = new SandboxDeployException(sandboxDeployException0);
      assertFalse(sandboxDeployException1.equals((Object)sandboxDeployException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SandboxDeployException sandboxDeployException0 = new SandboxDeployException("");
      SandboxDeployException sandboxDeployException1 = new SandboxDeployException((String) null, sandboxDeployException0);
      assertFalse(sandboxDeployException1.equals((Object)sandboxDeployException0));
  }
}
