/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:44:49 GMT 2017
 */

package com.liferay.portal.kernel.deploy.sandbox;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.deploy.sandbox.SandboxDeployDir;
import com.liferay.portal.kernel.deploy.sandbox.SandboxDeployListener;
import com.liferay.portal.kernel.deploy.sandbox.SandboxDeployScanner;
import java.io.File;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SandboxDeployScanner_ESTest extends SandboxDeployScanner_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ThreadGroup threadGroup0 = new ThreadGroup("");
      MockFile mockFile0 = new MockFile((File) null, "");
      LinkedList<SandboxDeployListener> linkedList0 = new LinkedList<SandboxDeployListener>();
      SandboxDeployDir sandboxDeployDir0 = new SandboxDeployDir("7&L;3w=2PD&)/;U", mockFile0, (-1L), linkedList0);
      SandboxDeployScanner sandboxDeployScanner0 = new SandboxDeployScanner(threadGroup0, "", sandboxDeployDir0);
      // Undeclared exception!
      try { 
        sandboxDeployScanner0.run();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // timeout value is negative
         //
         verifyException("java.lang.Thread", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ThreadGroup threadGroup0 = new ThreadGroup("");
      LinkedList<SandboxDeployListener> linkedList0 = new LinkedList<SandboxDeployListener>();
      SandboxDeployDir sandboxDeployDir0 = new SandboxDeployDir((String) null, (File) null, (-312L), linkedList0);
      SandboxDeployScanner sandboxDeployScanner0 = null;
      try {
        sandboxDeployScanner0 = new SandboxDeployScanner(threadGroup0, (String) null, sandboxDeployDir0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // name cannot be null
         //
         verifyException("java.lang.Thread", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ThreadGroup threadGroup0 = new ThreadGroup("'IZ=l, N\"MRZ'v ZG");
      MockFile mockFile0 = new MockFile("gl", "gl");
      threadGroup0.destroy();
      LinkedList<SandboxDeployListener> linkedList0 = new LinkedList<SandboxDeployListener>();
      SandboxDeployDir sandboxDeployDir0 = new SandboxDeployDir("gl", mockFile0, 1366L, linkedList0);
      SandboxDeployScanner sandboxDeployScanner0 = null;
      try {
        sandboxDeployScanner0 = new SandboxDeployScanner(threadGroup0, "gl", sandboxDeployDir0);
        fail("Expecting exception: IllegalThreadStateException");
      
      } catch(IllegalThreadStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.ThreadGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<SandboxDeployListener> linkedList0 = new LinkedList<SandboxDeployListener>();
      SandboxDeployDir sandboxDeployDir0 = new SandboxDeployDir("GmfF*3bZX", (File) null, 0L, linkedList0);
      SandboxDeployScanner sandboxDeployScanner0 = new SandboxDeployScanner((ThreadGroup) null, "GmfF*3bZX", sandboxDeployDir0);
      // Undeclared exception!
      try { 
        sandboxDeployScanner0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.deploy.sandbox.SandboxDeployDir", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ThreadGroup threadGroup0 = new ThreadGroup("aNwI6|Ah\"8");
      MockFile mockFile0 = new MockFile("aNwI6|Ah\"8", "aNwI6|Ah\"8");
      LinkedList<SandboxDeployListener> linkedList0 = new LinkedList<SandboxDeployListener>();
      SandboxDeployDir sandboxDeployDir0 = new SandboxDeployDir("aNwI6|Ah\"8", mockFile0, 1479L, linkedList0);
      SandboxDeployScanner sandboxDeployScanner0 = new SandboxDeployScanner(threadGroup0, "aNwI6|Ah\"8", sandboxDeployDir0);
      sandboxDeployScanner0.pause();
      sandboxDeployScanner0.run();
      assertTrue(sandboxDeployScanner0.isDaemon());
  }
}
