/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:10:03 GMT 2017
 */

package com.liferay.portal.kernel.bi.rules;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.bi.rules.Fact;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Fact_ESTest extends Fact_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Fact<Object> fact0 = new Fact<Object>((String) null, (Object) null);
      String string0 = fact0.getIdentifier();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Fact<String> fact0 = new Fact<String>("com.liferay.portal.kernel.bi.rules.Fact", "com.liferay.portal.kernel.bi.rules.Fact");
      String string0 = fact0.getIdentifier();
      assertEquals("com.liferay.portal.kernel.bi.rules.Fact", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Fact<Object> fact0 = new Fact<Object>((String) null, (Object) null);
      Object object0 = fact0.getFactObject();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Fact<String> fact0 = new Fact<String>("com.liferay.portal.kernel.bi.rules.Fact", "com.liferay.portal.kernel.bi.rules.Fact");
      String string0 = fact0.getFactObject();
      assertEquals("com.liferay.portal.kernel.bi.rules.Fact", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Object object0 = new Object();
      Fact<Object> fact0 = new Fact<Object>("", object0);
      String string0 = fact0.getIdentifier();
      assertEquals("", string0);
  }
}
