/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:04:41 GMT 2017
 */

package com.liferay.portal.kernel.bi.reporting.messaging;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.bi.reporting.ByteArrayReportResultContainer;
import com.liferay.portal.kernel.bi.reporting.ContextClassloaderReportDesignRetriever;
import com.liferay.portal.kernel.bi.reporting.ReportDataSourceType;
import com.liferay.portal.kernel.bi.reporting.ReportEngine;
import com.liferay.portal.kernel.bi.reporting.ReportRequest;
import com.liferay.portal.kernel.bi.reporting.ReportRequestContext;
import com.liferay.portal.kernel.bi.reporting.messaging.ReportRequestMessageListener;
import com.liferay.portal.kernel.messaging.Message;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReportRequestMessageListener_ESTest extends ReportRequestMessageListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ByteArrayReportResultContainer byteArrayReportResultContainer0 = new ByteArrayReportResultContainer();
      ReportRequestMessageListener reportRequestMessageListener0 = new ReportRequestMessageListener((ReportEngine) null, byteArrayReportResultContainer0);
      Message message0 = new Message();
      ReportDataSourceType reportDataSourceType0 = ReportDataSourceType.PORTAL;
      ReportRequestContext reportRequestContext0 = new ReportRequestContext(reportDataSourceType0);
      ContextClassloaderReportDesignRetriever contextClassloaderReportDesignRetriever0 = new ContextClassloaderReportDesignRetriever("jdbc.driverClassName");
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      ReportRequest reportRequest0 = new ReportRequest(reportRequestContext0, contextClassloaderReportDesignRetriever0, hashMap0, "pdf");
      message0.setPayload(reportRequest0);
      // Undeclared exception!
      try { 
        reportRequestMessageListener0.receive(message0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.messaging.MessageBusUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ByteArrayReportResultContainer byteArrayReportResultContainer0 = new ByteArrayReportResultContainer();
      ReportRequestMessageListener reportRequestMessageListener0 = new ReportRequestMessageListener((ReportEngine) null, byteArrayReportResultContainer0);
      Message message0 = new Message();
      Object object0 = new Object();
      message0.setPayload(object0);
      // Undeclared exception!
      try { 
        reportRequestMessageListener0.receive(message0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to com.liferay.portal.kernel.bi.reporting.ReportRequest
         //
         verifyException("com.liferay.portal.kernel.bi.reporting.messaging.ReportRequestMessageListener", e);
      }
  }
}
