/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:47:57 GMT 2017
 */

package com.liferay.portal.kernel.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.exception.PortalException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PortalException_ESTest extends PortalException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("V");
      PortalException portalException0 = new PortalException("V", mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PortalException portalException0 = new PortalException("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("V");
      PortalException portalException0 = new PortalException(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PortalException portalException0 = new PortalException();
  }
}
