/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:48:06 GMT 2017
 */

package com.liferay.portal.kernel.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.exception.SystemException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SystemException_ESTest extends SystemException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemException systemException0 = new SystemException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SystemException systemException0 = new SystemException(" 'ximR}h/jJD>bn41j", (Throwable) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SystemException systemException0 = new SystemException(" 'ximR}h/jJD>bn41j");
      SystemException systemException1 = new SystemException(systemException0);
      assertFalse(systemException1.equals((Object)systemException0));
  }
}
