/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 23:41:58 GMT 2017
 */

package com.liferay.portal.kernel.captcha;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.captcha.CaptchaMaxChallengesException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CaptchaMaxChallengesException_ESTest extends CaptchaMaxChallengesException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CaptchaMaxChallengesException captchaMaxChallengesException0 = new CaptchaMaxChallengesException("com.liferay.portal.kernel.exception.NestableException");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CaptchaMaxChallengesException captchaMaxChallengesException0 = new CaptchaMaxChallengesException();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("eI,8Ye<[s)T-U+$)");
      CaptchaMaxChallengesException captchaMaxChallengesException0 = new CaptchaMaxChallengesException("8XLb0R", mockThrowable0);
      CaptchaMaxChallengesException captchaMaxChallengesException1 = new CaptchaMaxChallengesException(captchaMaxChallengesException0);
      assertFalse(captchaMaxChallengesException1.equals((Object)captchaMaxChallengesException0));
  }
}
