/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:46:28 GMT 2017
 */

package com.liferay.portal.kernel.events;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.events.InvokerSimpleAction;
import com.liferay.portal.kernel.events.SimpleAction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InvokerSimpleAction_ESTest extends InvokerSimpleAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleAction simpleAction0 = mock(SimpleAction.class, new ViolatedAssumptionAnswer());
      InvokerSimpleAction invokerSimpleAction0 = new InvokerSimpleAction(simpleAction0);
      String[] stringArray0 = new String[2];
      invokerSimpleAction0.run(stringArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleAction simpleAction0 = mock(SimpleAction.class, new ViolatedAssumptionAnswer());
      InvokerSimpleAction invokerSimpleAction0 = new InvokerSimpleAction(simpleAction0);
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      InvokerSimpleAction invokerSimpleAction1 = new InvokerSimpleAction(invokerSimpleAction0, classLoader0);
      assertFalse(invokerSimpleAction1.equals((Object)invokerSimpleAction0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      InvokerSimpleAction invokerSimpleAction0 = new InvokerSimpleAction((SimpleAction) null);
      String[] stringArray0 = new String[5];
      // Undeclared exception!
      try { 
        invokerSimpleAction0.run(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.events.InvokerSimpleAction", e);
      }
  }
}
