/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:47:40 GMT 2017
 */

package com.liferay.portal.kernel.events;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.events.InvokerSimpleAction;
import com.liferay.portal.kernel.events.SimpleAction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleAction_ESTest extends SimpleAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      InvokerSimpleAction invokerSimpleAction0 = new InvokerSimpleAction((SimpleAction) null, classLoader0);
      String[] stringArray0 = new String[5];
      // Undeclared exception!
      try { 
        invokerSimpleAction0.run(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.events.InvokerSimpleAction", e);
      }
  }
}
