/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Dec 08 22:31:04 GMT 2017
 */

package com.liferay.counter.service;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CounterLocalServiceWrapper_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.liferay.counter.service.CounterLocalServiceWrapper"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CounterLocalServiceWrapper_ESTest_scaffolding.class.getClassLoader() ,
      "com.liferay.portal.kernel.bean.BeanPropertiesUtil",
      "com.liferay.portal.kernel.dao.orm.Criterion",
      "com.liferay.portal.kernel.annotation.Propagation",
      "com.liferay.portal.kernel.workflow.comparator.BaseWorkflowTaskDueDateComparator",
      "com.liferay.portal.kernel.annotation.Isolation",
      "com.liferay.counter.model.CounterModel",
      "com.liferay.portal.kernel.dao.orm.DynamicQuery",
      "com.liferay.portal.kernel.workflow.comparator.BaseWorkflowTaskNameComparator",
      "com.liferay.portal.service.ServiceContext",
      "com.liferay.portal.model.PortletPreferencesIds",
      "com.liferay.portal.kernel.exception.NestableException",
      "com.liferay.portlet.expando.model.ExpandoBridge",
      "com.liferay.counter.service.CounterLocalServiceWrapper",
      "com.liferay.portal.kernel.exception.PortalException",
      "com.liferay.portal.kernel.exception.SystemException",
      "com.liferay.portal.kernel.dao.orm.Session",
      "com.liferay.portal.kernel.dao.orm.Projection",
      "com.liferay.portal.kernel.dao.orm.Order",
      "com.liferay.portal.kernel.annotation.Transactional",
      "com.liferay.counter.service.CounterLocalService",
      "com.liferay.portal.model.BaseModel",
      "com.liferay.counter.model.Counter",
      "com.liferay.portal.kernel.util.OrderByComparator",
      "com.liferay.counter.model.CounterWrapper"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.liferay.counter.model.Counter", false, CounterLocalServiceWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.liferay.counter.service.CounterLocalService", false, CounterLocalServiceWrapper_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.liferay.portal.kernel.dao.orm.DynamicQuery", false, CounterLocalServiceWrapper_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CounterLocalServiceWrapper_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.liferay.portal.kernel.annotation.Isolation",
      "com.liferay.portal.kernel.annotation.Propagation",
      "com.liferay.counter.model.CounterWrapper",
      "com.liferay.portal.kernel.util.OrderByComparator",
      "com.liferay.portal.kernel.workflow.comparator.BaseWorkflowTaskDueDateComparator",
      "com.liferay.portal.kernel.workflow.comparator.BaseWorkflowTaskNameComparator",
      "com.liferay.portal.kernel.bean.BeanPropertiesUtil",
      "com.liferay.portal.service.ServiceContext"
    );
  }
}
