/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:51:31 GMT 2017
 */

package com.liferay.portal.kernel.googleapps;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.googleapps.GGroup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GGroup_ESTest extends GGroup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setPermissionPreset("B'NQ");
      String string0 = gGroup0.getPermissionPreset();
      assertEquals("B'NQ", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setName("");
      String string0 = gGroup0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setEmailPermission("7P");
      String string0 = gGroup0.getEmailPermission();
      assertEquals("7P", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setEmailPermission("");
      String string0 = gGroup0.getEmailPermission();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setEmailAddress("j\b2@3ttp");
      String string0 = gGroup0.getEmailAddress();
      assertEquals("j\b2@3ttp", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setEmailAddress("");
      String string0 = gGroup0.getEmailAddress();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setDescription("|zc-0T81_%Gk");
      String string0 = gGroup0.getDescription();
      assertEquals("|zc-0T81_%Gk", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setDescription("");
      String string0 = gGroup0.getDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setName("r_SnMf\" tKU.e49a");
      String string0 = gGroup0.getName();
      assertEquals("r_SnMf\" tKU.e49a", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      gGroup0.setPermissionPreset("");
      String string0 = gGroup0.getPermissionPreset();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      String string0 = gGroup0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      String string0 = gGroup0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      String string0 = gGroup0.getEmailAddress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      String string0 = gGroup0.getPermissionPreset();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GGroup gGroup0 = new GGroup();
      String string0 = gGroup0.getEmailPermission();
      assertNull(string0);
  }
}
