/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:55:23 GMT 2017
 */

package com.liferay.portal.kernel.googleapps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.googleapps.GoogleAppsFactory;
import com.liferay.portal.kernel.googleapps.GoogleAppsFactoryUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GoogleAppsFactoryUtil_ESTest extends GoogleAppsFactoryUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        GoogleAppsFactoryUtil.getGNicknameManager((-2326L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.GoogleAppsFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GoogleAppsFactoryUtil googleAppsFactoryUtil0 = new GoogleAppsFactoryUtil();
      googleAppsFactoryUtil0.setGoogleAppsFactory((GoogleAppsFactory) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        GoogleAppsFactoryUtil.getGGroupManager((-1238L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.GoogleAppsFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        GoogleAppsFactoryUtil.getGUserManager((-914L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.GoogleAppsFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        GoogleAppsFactoryUtil.getGEmailSettingsManager(3227L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.GoogleAppsFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GoogleAppsFactory googleAppsFactory0 = GoogleAppsFactoryUtil.getGoogleAppsFactory();
      assertNull(googleAppsFactory0);
  }
}
