/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:54:14 GMT 2017
 */

package com.liferay.portal.kernel.googleapps;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.googleapps.GoogleAppsException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GoogleAppsException_ESTest extends GoogleAppsException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GoogleAppsException googleAppsException0 = new GoogleAppsException("Q6})Wj;AugtKw`Qhh//");
      GoogleAppsException googleAppsException1 = new GoogleAppsException("Q6})Wj;AugtKw`Qhh//", googleAppsException0);
      assertFalse(googleAppsException1.equals((Object)googleAppsException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GoogleAppsException googleAppsException0 = new GoogleAppsException();
      GoogleAppsException googleAppsException1 = new GoogleAppsException(googleAppsException0);
      assertFalse(googleAppsException1.equals((Object)googleAppsException0));
  }
}
