/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:56:35 GMT 2017
 */

package com.liferay.portal.kernel.googleapps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.googleapps.GUser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GUser_ESTest extends GUser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setAdministrator(true);
      boolean boolean0 = gUser0.isAdministrator();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setActive(true);
      boolean boolean0 = gUser0.isActive();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setUserId((-2944L));
      long long0 = gUser0.getUserId();
      assertEquals((-2944L), long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setLastName("goC<");
      String string0 = gUser0.getLastName();
      assertEquals("goC<", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setFirstName("goC<");
      gUser0.setLastName("goC<");
      String string0 = gUser0.getFullName();
      assertEquals("goC< goC<", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setFirstName("i");
      String string0 = gUser0.getFirstName();
      assertEquals("i", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setFirstName("");
      String string0 = gUser0.getFirstName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setLastName("");
      String string0 = gUser0.getLastName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GUser gUser0 = new GUser();
      long long0 = gUser0.getUserId();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setUserId(1L);
      long long0 = gUser0.getUserId();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GUser gUser0 = new GUser();
      boolean boolean0 = gUser0.isAgreedToTermsOfUse();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GUser gUser0 = new GUser();
      gUser0.setAgreedToTermsOfUse(true);
      boolean boolean0 = gUser0.isAgreedToTermsOfUse();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GUser gUser0 = new GUser();
      boolean boolean0 = gUser0.isAdministrator();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GUser gUser0 = new GUser();
      boolean boolean0 = gUser0.isActive();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GUser gUser0 = new GUser();
      // Undeclared exception!
      try { 
        gUser0.getFullName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.googleapps.GUser", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GUser gUser0 = new GUser();
      String string0 = gUser0.getFirstName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GUser gUser0 = new GUser();
      String string0 = gUser0.getLastName();
      assertNull(string0);
  }
}
