/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 09 00:40:54 GMT 2017
 */

package com.liferay.portal.kernel.deploy.hot;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.deploy.hot.HotDeployException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HotDeployException_ESTest extends HotDeployException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HotDeployException hotDeployException0 = new HotDeployException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HotDeployException hotDeployException0 = new HotDeployException("vNHw77P-)`8{K", (Throwable) null);
      HotDeployException hotDeployException1 = new HotDeployException(hotDeployException0);
      assertFalse(hotDeployException1.equals((Object)hotDeployException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HotDeployException hotDeployException0 = new HotDeployException("vNHw77P-)`8{K");
  }
}
