/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:53:47 GMT 2017
 */

package com.liferay.portal.kernel.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liferay.portal.kernel.bean.BeanLocatorException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BeanLocatorException_ESTest extends BeanLocatorException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BeanLocatorException beanLocatorException0 = new BeanLocatorException();
      BeanLocatorException beanLocatorException1 = new BeanLocatorException("", beanLocatorException0);
      assertFalse(beanLocatorException1.equals((Object)beanLocatorException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BeanLocatorException beanLocatorException0 = new BeanLocatorException();
      BeanLocatorException beanLocatorException1 = new BeanLocatorException(beanLocatorException0);
      assertFalse(beanLocatorException1.equals((Object)beanLocatorException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BeanLocatorException beanLocatorException0 = new BeanLocatorException("org.evosuite.runtime.mock.java.lang.MockThrowable");
  }
}
