/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:55:06 GMT 2017
 */

package com.liferay.portal.kernel.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.bean.ClassLoaderBeanHandler;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClassLoaderBeanHandler_ESTest extends ClassLoaderBeanHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderBeanHandler classLoaderBeanHandler0 = new ClassLoaderBeanHandler("V", classLoader0);
      ClassLoader classLoader1 = classLoaderBeanHandler0.getClassLoader();
      assertSame(classLoader0, classLoader1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderBeanHandler classLoaderBeanHandler0 = new ClassLoaderBeanHandler("V", classLoader0);
      Object object0 = classLoaderBeanHandler0.getBean();
      assertEquals("V", object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderBeanHandler classLoaderBeanHandler0 = new ClassLoaderBeanHandler("V", classLoader0);
      Object[] objectArray0 = new Object[8];
      try { 
        classLoaderBeanHandler0.invoke(objectArray0[2], (Method) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.bean.ClassLoaderBeanHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ClassLoaderBeanHandler classLoaderBeanHandler0 = new ClassLoaderBeanHandler((Object) null, (ClassLoader) null);
      try { 
        classLoaderBeanHandler0.invoke((Object) null, (Method) null, (Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.bean.ClassLoaderBeanHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ClassLoaderBeanHandler classLoaderBeanHandler0 = new ClassLoaderBeanHandler((Object) null, (ClassLoader) null);
      Object object0 = classLoaderBeanHandler0.getBean();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ClassLoaderBeanHandler classLoaderBeanHandler0 = new ClassLoaderBeanHandler("", (ClassLoader) null);
      ClassLoader classLoader0 = classLoaderBeanHandler0.getClassLoader();
      assertNull(classLoader0);
  }
}
