/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:50:09 GMT 2017
 */

package com.liferay.portal.kernel.audit;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.audit.AuditMessageFactory;
import com.liferay.portal.kernel.audit.AuditMessageFactoryUtil;
import com.liferay.portal.kernel.json.JSONObject;
import java.util.Date;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuditMessageFactoryUtil_ESTest extends AuditMessageFactoryUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("xA'8#]b|1YI*n8", 2300L, 639L, (String) null, "xA'8#]b|1YI*n8", (String) null, "w1:4|q9", (JSONObject) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      MockDate mockDate0 = new MockDate(0L);
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("sessionID", (-2792L), 0L, "sessionID", "-9", "-9", "sessionID", (Date) mockDate0, (JSONObject) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("  AmBh>wV[uN", (-434L), (-434L), "  AmBh>wV[uN", "  AmBh>wV[uN", "timestamp", "  AmBh>wV[uN");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage((String) null, 2532L, (-383L), "clientHost", "clientHost", (String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("serverName", 1828L, 1828L, (String) null, (String) null, "serverName");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AuditMessageFactory auditMessageFactory0 = AuditMessageFactoryUtil.getAuditMessageFactory();
      assertNull(auditMessageFactory0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      auditMessageFactoryUtil0.setAuditMessageFactory((AuditMessageFactory) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("PjjTbes#", 0L, 2095L, (String) null, "", "PjjTbes#", "", (JSONObject) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", 456L, (-1265L), "iqor");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      MockDate mockDate0 = new MockDate(1798L);
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("sessionID", 1798L, 1327L, "[WMef{Ex8#MJsOl{,C0", "[WMef{Ex8#MJsOl{,C0", "com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", "", (Date) mockDate0, (JSONObject) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("Z`c NF4g");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("", 0L, (-74L), "", "sessionID", "com.liferay.portal.kernel.exception.NestableException");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AuditMessageFactoryUtil auditMessageFactoryUtil0 = new AuditMessageFactoryUtil();
      // Undeclared exception!
      try { 
        auditMessageFactoryUtil0.getAuditMessage("", 1L, 80L, "Y4A%t[piLJUn", "", "!0]!cx", "!0]!cx");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditMessageFactoryUtil", e);
      }
  }
}
