/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 08 22:52:30 GMT 2017
 */

package com.liferay.portal.kernel.audit;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.audit.AuditMessage;
import com.liferay.portal.kernel.audit.AuditRouter;
import com.liferay.portal.kernel.audit.AuditRouterUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuditRouterUtil_ESTest extends AuditRouterUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuditRouterUtil auditRouterUtil0 = new AuditRouterUtil();
      auditRouterUtil0.setAuditRouter((AuditRouter) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AuditRouter auditRouter0 = AuditRouterUtil.getAuditRouter();
      assertNull(auditRouter0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        AuditRouterUtil.route((AuditMessage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.audit.AuditRouterUtil", e);
      }
  }
}
